version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 14
  pre_build:
    commands:
      - npm update -g npm
      - npm install --production
  build:
    commands:
      - npm run build
artifacts:
  files:
    - '**/*'
  base-directory: 'build'