---
swagger: "2.0"
info:
  version: "2021-12-14T17:08:02Z"
  title: "cdksnippetApi"
basePath: "/api"
schemes:
- "https"
paths:
  /test:
    get:
      responses:
        "200":
          description: "200 response"
      security:
      - cdksnippetauthz: []
      x-amazon-apigateway-integration:
        httpMethod: "POST"
        uri: "arn:aws:apigateway:ap-northeast-1:lambda:path/2015-03-31/functions/arn:aws:lambda:ap-northeast-1:************:function:cdksnippetFunc/invocations"
        passthroughBehavior: "when_no_match"
        type: "aws_proxy"
  /test/test:
    get:
      responses:
        "200":
          description: "200 response"
      security:
      - cdksnippetauthz: []
      x-amazon-apigateway-integration:
        httpMethod: "POST"
        uri: "arn:aws:apigateway:ap-northeast-1:lambda:path/2015-03-31/functions/arn:aws:lambda:ap-northeast-1:************:function:cdksnippetFunc/invocations"
        passthroughBehavior: "when_no_match"
        type: "aws_proxy"
securityDefinitions:
  cdksnippetauthz:
    type: "apiKey"
    name: "Authorization"
    in: "header"
    x-amazon-apigateway-authtype: "custom"
    x-amazon-apigateway-authorizer:
      authorizerUri: "arn:aws:apigateway:ap-northeast-1:lambda:path/2015-03-31/functions/arn:aws:lambda:ap-northeast-1:************:function:authorizer/invocations"
      authorizerResultTtlInSeconds: 300
      identitySource: "method.request.header.Authorization"
      type: "request"
